#! /bin/sh

WEBDIR="$( dirname $( readlink -e $0 ) )"
# XXX:UBUNTU GNU-ism.

# These are the Ubuntu defaults.  /usr/sbin is often not on our PATH
# We need to override for local installs
APACHE2=/usr/sbin/apache2
export APACHE2_MODS=/usr/lib/apache2/modules
export APACHE2_SHARE=/usr/share/apache2

# required vars, not always set from cron
: ${USER:=$(whoami)}
: ${HOME:=$(bash -c 'echo ~')} # ugh


op=$( basename $0 )
if [ "$op" = 'APACHECTL' ]; then
    op=$1
    shift
fi

apache_defines() {
    local tok out
    for tok in $( echo ${WEBDEFS:-vanilla} | tr , ' ' ); do
	out="$out -D $( echo "$tok" | tr '[:lower:]' '[:upper:]' )"
    done
    echo "$out"
}

[ -f "$WEBDIR/APACHECTL.sh" ] && {
    echo "[d] source $WEBDIR/APACHECTL.sh"
    . "$WEBDIR/APACHECTL.sh"
}

: ${WEBTMPDIR:="$( dirname "$WEBDIR" )/tmp/$( basename "$WEBDIR" )"}
[ -d "$WEBTMPDIR" ] && [ -w "$WEBTMPDIR" ] || {
    echo "Abort: Guessed WEBTMPDIR=$WEBTMPDIR incorrectly, please have it created & writable, or override by environment" >&2
    exit 2
}

# Export these because Apache needs to interpolate them into the config
export WEBDIR WEBTMPDIR

echo "[d] doing $op for WEBDIR=$WEBDIR WEBTMPDIR=$WEBTMPDIR with" $( apache_defines )
case $op in
    '' | -h | --help)
        cat <<INFO
Syntax: APACHECTL < \$operation > [args]*
    or  run via a symlink, named for an operation

Operations delegated to the Apache2 httpd are
 start | restart | graceful | graceful-stop | stop

Other operations are names of executables in $WEBDIR/tools/
 checkmods     Compare available LoadModules against ServerRoot/mods-available/
 mkloadmods    Attempt to construct missing ServerRoot/mods-*/*.load

Environment variables affecting the run are documented in README.txt

INFO
        exit 0
        ;;
    start|restart|graceful|graceful-stop|stop) # supported by "apache2 -k"
        [ $# = 0 ] || echo "[w] $# extra argument(s) ignored" >&2
        exec $APACHE2 \
	    $( apache_defines ) \
            -f "$WEBDIR/ServerRoot/conf/httpd.conf" \
            -k $op
        ;;
    *)
        if [ -f "$WEBDIR/tools/$op" ] && [ -x "$WEBDIR/tools/$op" ]; then
            $WEBDIR/tools/$op "$@"
        else
            echo "Cannot comprehend op=$op" >&2
            exit 1
        fi
        ;;
esac

# not reached - exec | exit
