#! /bin/sh

WEBDIR="$( dirname $( readlink -e $0 ) )"
# XXX:UBUNTU GNU-ism.

: ${WEBTMPDIR:="$( dirname "$WEBDIR" )/tmp/$( basename "$WEBDIR" )"}
[ -d "$WEBTMPDIR" ] && [ -w "$WEBTMPDIR" ] || {
    echo "Abort: Guessed WEBTMPDIR=$WEBTMPDIR incorrectly, please override by environment" >&2
    exit 2
}

apache_defines() {
    local tok out
    for tok in $( echo ${WEBDEFS:-vanilla} | tr , ' ' ); do
	out="$out -D $( echo "$tok" | tr '[:lower:]' '[:upper:]' )"
    done
    echo "$out"
}

export WEBDIR WEBTMPDIR

op=${1:-$( basename $0 )}

echo "[d] doing $op for WEBDIR=$WEBDIR WEBTMPDIR=$WEBTMPDIR with" $( apache_defines )
case $op in
    -h | --help)
        cat <<INFO
Syntax: APACHECTL < start | stop | graceful >
    or  run via a symlink with one of these names

More options later.

INFO
        exit 0
        ;;
    start | stop | graceful)
        exec /usr/sbin/apache2 \
	    $( apache_defines )
            -f "$WEBDIR/ServerRoot/conf/httpd.conf" \
            -k $op
        ;;
    *)
        echo "Cannot comprehend op=$op" >&2
        exit 1
        ;;
esac

# not reached - exec | exit
