#!/bin/bash
# Copyright [2018-2019] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## Check we have any scripts!
t=`ls -1 $0.d/*.pl 2>/dev/null`;
if [ ${#t} -eq 0 ]; then exit 0; fi

## Start with a zero exit code!
EXIT_CODE=0

## Loop through each pl file in the appropriate .d directory
## e.g. for pre-commit it looks through pre-commit.d
for HOOK in $0.d/*.pl; do
  $HOOK $@
  ## Run $HOOK with the parameters passed into the script
  ## If it exits with an non-zero error code ($?), set final
  ## exit code to 1
  if [[ $? -ne 0 ]]; then 
    EXIT_CODE=1 
  fi
done

## Exit with the appropriate error code
exit $EXIT_CODE
