#! /bin/sh
# Copyright [2018-2024] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e
set -x
OUTDIR="/www/tmp/$USER/$(hostname -s).info"
mkdir -p "$OUTDIR"
COLUMNS=200 dpkg -l > "$OUTDIR/dpkg-l"
lsb_release -a > "$OUTDIR/lsb_release-a" 2>&1
find /www -ls > "$OUTDIR/find.www.-ls" 2>&1 || true
