#! /bin/sh
# Copyright [2018-2020] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



set -e
LC_ALL=C
DIR="$( mktemp -d --tmpdir webvm-checkmods.XXXXXX )"

trap "rm -f $DIR/present $DIR/listed_available; rmdir $DIR" EXIT
cd $DIR

perl -ne 'print "$1\n" if m{^\s*LoadModule\s.*/(\S+\.(?:so|dylib))$}' \
    $WEBDIR/ServerRoot/mods-available/*.load | sort \
    > listed_available

ls $APACHE2_MODS | grep -vE '\.(exp|a|la)' | sort \
    > present

set +e

diff -u present listed_available
