#! /bin/sh
# Copyright [2018-2022] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e
cd "$WEBDIR"

in_dir="$1"
shift
git_op="$2"

case "$in_dir" in
    /*|*..*)
        echo "Give working directory spec relative to $WEBDIR" >&2
        exit 3
        ;;
esac

if [ -n "$in_dir" ] && [ -d "$in_dir/.git" ] && [ -O "$in_dir/.git" ] && [ -n "$*" ]; then
    # OK
    cd "$in_dir"
    exec git "$@"
fi

printf "Syntax: utilities/git-in <dir> <git-op> <args>*\n
Where dir should be one of\n"
find . -depth -name .git -type d -printf "  %h\n"
exit 4
