#! /bin/sh
# Copyright [2018-2021] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# Not sure this hack would be needed, but since I pushed Subversion
# working copies into Git and their empty directories got lost,
# I must assume it could be necessary to replace them.
#


### I suspect this would do it just fine, but not all were present
#
#for d in $( find $WEBDIR/utilities -type d -name .svn ); do
#    echo ==== $d
#    mkdir -pv $d/{,tmp/}{prop-base,props,text-base}
#done


set -e
cd "$WEBDIR"
# These were actually present at 890ae173
mkdir -p \
  utilities/.svn/props/ \
  utilities/.svn/tmp/ \
  utilities/link-checker/.svn/prop-base/ \
  utilities/link-checker/.svn/props/ \
  utilities/link-checker/.svn/text-base/ \
  utilities/link-checker/.svn/tmp/ \
  utilities/maint/.svn/prop-base/ \
  utilities/maint/.svn/props/ \
  utilities/maint/.svn/text-base/ \
  utilities/maint/.svn/tmp/ \
  utilities/svn-utils/.svn/prop-base/ \
  utilities/svn-utils/.svn/props/ \
  utilities/svn-utils/.svn/text-base/ \
  utilities/svn-utils/.svn/tmp/ \
  utilities/svn/.svn/props/ \
  utilities/svn/.svn/tmp/ \
  utilities/svn/post-commit.d/.svn/props/ \
  utilities/svn/post-commit.d/.svn/tmp/ \
  utilities/svn/post-lock.d/.svn/prop-base/ \
  utilities/svn/post-lock.d/.svn/props/ \
  utilities/svn/post-lock.d/.svn/text-base/ \
  utilities/svn/post-lock.d/.svn/tmp/ \
  utilities/svn/post-revprop-change.d/.svn/props/ \
  utilities/svn/post-revprop-change.d/.svn/tmp/ \
  utilities/svn/post-unlock.d/.svn/prop-base/ \
  utilities/svn/post-unlock.d/.svn/props/ \
  utilities/svn/post-unlock.d/.svn/text-base/ \
  utilities/svn/post-unlock.d/.svn/tmp/ \
  utilities/svn/pre-commit.d/.svn/props/ \
  utilities/svn/pre-commit.d/.svn/tmp/ \
  utilities/svn/pre-lock.d/.svn/props/ \
  utilities/svn/pre-lock.d/.svn/tmp/ \
  utilities/svn/pre-unlock.d/.svn/props/ \
  utilities/svn/pre-unlock.d/.svn/tmp/ \
  utilities/svn/start-commit.d/.svn/props/ \
  utilities/svn/start-commit.d/.svn/tmp/
